run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - noctx
    - revive
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  goconst:
    min-occurrences: 3
    ignore-tests: true
  misspell:
    locale: UK
    ignore-words:
      - fiber
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: increment-decrement
      - name: var-declaration
      - name: unexported-return

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
