version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - revive
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    goconst:
      min-occurrences: 3
    misspell:
      locale: UK
      ignore-rules:
        - fiber
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: increment-decrement
        - name: var-declaration
        - name: unexported-return
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - bodyclose
          - goconst

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
